name: Terraform CI

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:


jobs:
  terraform-checks:
    name: aws-terraform-private-runner
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init Without Backend
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate
